import { Helmet } from 'react-helmet';

import Logo from './logo.component.svg';

const Home = (): JSX.Element => (
  <>
    <Helmet>
      <title>Home Page</title>
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta name="description" content="Home page" />
    </Helmet>
    <div>
      <Logo />
      <p>
        This project generated by <strong>Rockpack</strong>. Please read official{' '}
        <a href="https://alexsergey.github.io/rockpack/" target="_blank" rel="noopener noreferrer">
          documentation
        </a>
        .
      </p>
    </div>
  </>
);

export default Home;
