version: '3.9'

services:
  db_test:
    image: mysql:5.7
    container_name: db_test
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - dbdata_test:/var/lib/mysql_test
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_PASSWORD=${DB_USER_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_DATABASE=${DB_NAME}

volumes:
  dbdata_test:
