import { ReactElement } from 'react';

import Logo from './components/logo.component.svg';
import { useRockpack } from './hooks/rockpack-description.hooks';
import * as styles from './styles/styles.module.scss';

export const App = (): ReactElement => {
  const [, , description] = useRockpack();

  return (
    <div className={styles.wrapper}>
      <Logo />
      <p>{description}</p>
      <p>
        This project generated by <strong>Rockpack</strong>. Please read official{' '}
        <a href="https://alexsergey.github.io/rockpack/" rel="noopener noreferrer" target="_blank">
          documentation
        </a>
        .
      </p>
    </div>
  );
};
